[workspace]
members = [
  "central",
  "cli",
  "cli_macros",
  "registry",
  "registry_macros",
  "cliff",
  "cliff_macros",
  "note_store",
  "examples/calc",
  "examples/tasks",
]

[profile.release]
lto = true
