[workspace]
members = [
  # Core
  "macros",
  "registry",
  "cliff",
  "models",
  "codec",
  # Providers
  "note_repo",
  "note_store",
  "project_store",
  # Interfaces
  "central_cli",
]

[profile.release]
lto = true
